import { Routes } from '@angular/router';

export const routes: Routes = [
    {
        path:'',
        loadComponent:()=>import('./pages/home/home.component').then((c)=>c.HomeComponent)
    },
    {
        path:'header',
        loadComponent:()=>import('./main-app/header/header.component').then((c)=>c.HeaderComponent)
    },
    {
        path:'footer',
        loadComponent:()=>import('./main-app/footer/footer.component').then((c)=>c.FooterComponent)
    },
    {
        path:'login',
        loadComponent:()=>import('./pages/login/login.component').then((c)=>c.LoginComponent)
    },
    {
        path:'register',
        loadComponent:()=>import('./pages/register/register.component').then((c)=>c.RegisterComponent)
    },
    {
        path:'footer',
        loadComponent:()=>import('./main-app/footer/footer.component').then((c)=>c.FooterComponent)
    },
    {
        path:'header',
        loadComponent:()=>import('./main-app/header/header.component').then((c)=>c.HeaderComponent)
    },
    {
        path:'about',
        loadComponent:()=>import('./pages/about/about.component').then((c)=>c.AboutComponent)
    },
    {
        path:'profilework',
        loadComponent:()=>import('./pages/profiles/profiles.component').then((c)=>c.ProfilesComponent)
    },
    {
        path:'forgot-password',
        loadComponent:()=>import('./pages/forgot-password/forgot-password.component').then((c)=>c.ForgotPasswordComponent)
    },
    {
        path:'varify-email',
        loadComponent:()=>import('./pages/varify-email/varify-email.component').then((c)=>c.VarifyEmailComponent)
    },
    {
        path:'roles',
        loadComponent:()=>import('./pages/roles/roles.component').then((c)=>c.RolesComponent)
    },
    {
        path:'buffer',
        loadComponent:()=>import('./externalpages/buffer/buffer.component').then((c)=>c.BufferComponent)
    },
    {
        path:'landingpage',
        loadComponent:()=>import('./pages/landingpage/landingpage.component').then((c)=>c.LandingpageComponent)
    }
];
